[project]
name = "map"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.131.0",
    "sqlmodel>=0.0.37",
    "uvicorn[standard]>=0.41.0",
]
